execute pathogen#infect()

let mapleader = "-"

set backspace=indent,eol,start
set number
set relativenumber

syntax on
filetype plugin indent on

set t_Co=256
let g:rehash256 = 1

set background=dark
colorscheme Tomorrow-Night-Eighties

let g:go_fmt_command = "gofmt"
" let g:go_fmt_fail_silently = 1
let g:go_disable_autoinstall = 1

" Remove trailing spaces.
command! -nargs=0 WS %s/\s\+$//gce

" convert hash for ruby
command! -nargs=0 CH :%s/:\([^ ]*\)\(\s*\)=>/\1:/g

command! -nargs=0 JSON %!python -m json.tool

set laststatus=2
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts = 1

set autoindent          " automatically indent new line
set ts=4                " number of spaces in a tab
set sw=4                " number of spaces for indent
set et                  " expand tabs into spaces

autocmd Filetype javascript setlocal ts=4 sw=4 sts=0 noexpandtab
autocmd FileType sh setlocal ai sts=8 sw=8 noet
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd FileType python setlocal ts=4 sts=4 sw=4 tw=80 et si ai
autocmd Filetype ruby,eruby,yaml setlocal ts=2 sw=2 ai et expandtab

" Daima düzenlenen dosyanın bulunduğu dizine geç.
" autocmd BufEnter * lcd %:p:h

" Dosyayı düzenlerken kursörü en son bilinen konuma al.
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \	execute "normal g`\"" |
            \ endif

" Aşağıdaki kelimeleri daima renklendir.
autocmd BufRead,BufNewFile * syntax keyword Todo TODO XXX FIXME

nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Leader><Enter> <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. <Leader>aip)
nmap <Leader>a <Plug>(EasyAlign)

let g:gitgutter_sign_added = 'a'
let g:gitgutter_sign_modified = 'm'
let g:gitgutter_sign_removed = 'd'

highlight clear SignColumn

let g:syntastic_ruby_checkers = ['rubocop']

let g:multi_cursor_next_key='<C-d>'

map <C-n> :Explore<cr>

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

let g:rspec_command = "!bundle exec rspec -f d -c {spec}"

set hlsearch " highlight the search
set incsearch

" clear search
map <silent> <space><space> :let @/=''<CR>

" buffer
set autoread

set clipboard+=unnamed
" explore level
let g:netrw_liststyle=3

" keep blocks selected when indenting
vnoremap < <gv
vnoremap > >gv

set wildmenu
set wildmode=full
set scrolloff=3
set cursorline

let g:vimrubocop_config = '~/_/dotfiles/rubocop.yml'

let g:vimrubocop_keymap = 0
nmap <Leader>r :RuboCop<CR>

set fillchars-="vert:|"

hi VertSplit ctermbg=58 guibg=None
hi Split ctermbg=58 guibg=None

" let g:airline#extensions#tabline#enabled = 1
nmap <Tab><Tab> :CtrlPBuffer <CR>

" Enable mouse events
if has("mouse")
  set mouse=a
endif
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
